# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-27 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django02', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
