# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-27 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django02', '0013_student2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='student1',
        ),
        migrations.DeleteModel(
            name='student2',
        ),
    ]
