# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django02', '0017_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name1',
            field=models.CharField(default='', max_length=30),
        ),
    ]
