# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wenzhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
